// Copyright 2019 Preferred Networks, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

# Log level defined by sirupsen/logrus.
# Optional (default: info)
logLevel: debug

# Interval duration for scheduling and updating the cluster, in seconds.
# Optional (default: 10)
tick: 10

# Start time at which the simulation starts, in RFC3339 format.
# Optional (default: now)
startClock: 2019-01-01T00:00:00+09:00

# Interval duration for logging metrics of the cluster, in seconds.
# Optional (default: same as tick)
metricsTick: 60

# Metrics of simulated kubernetes cluster is written to a file at this path.
# The metrics is formatted with the given formatter.
# Optional (default: not writing metrics to a file)
metricsFile:
- path: kubesim.log
  formatter: JSON
- path: kubesim-hr.log
  formatter: humanReadable

# Metrics is (also) written to stdout.
# Optional (default: not writing metrics to stdout)
metricsStdout:
  formatter: table

# Write configuration of each node.
cluster:
- metadata:
    name: node-0
    labels:
      beta.kubernetes.io/os: simulated
    annotations:
      foo: bar
  spec:
    unschedulable: false
    # taints:
    # - key: k
    #   value: v
    #   effect: NoSchedule
  status:
    allocatable:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1
      pods: 2
- metadata:
    name: node-1
    labels:
      beta.kubernetes.io/os: simulated
    # annotations:
  spec:
    unschedulable: false
    # taints:
  status:
    allocatable:
      cpu: 8
      memory: 16Gi
      nvidia.com/gpu: 2
      pods: 4
