language: go
go:
- "1.11.x"

addons:
  apt:
    packages:
    - python3
    - python3-pip

before_install:
- export PATH=$GOPATH/bin:$PATH

install:
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
- go get -u github.com/mattn/goveralls
- pip3 install --user toml

script:
- make lint test coverage
- goveralls -coverprofile=profile.cov -service=travis-ci
- make e2e
- python3 ./scripts/license/check.py -v
- python3 ./scripts/check_dep_list.py -v
