[[constraint]]
  name = "github.com/cpuguy83/strongerrors"
  version = "~0.2.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.3.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "~2.2.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.14.0-rc.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0-rc.1"

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "~1.2.5"

[prune]
  go-tests = true
  unused-packages = true


# Dependencies for example

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
